pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
      sh 'apk add --update nodejs npm'
      sh 'node --version'
      
      // Install any dependencies or run additional setup if needed
      sh 'npm --version'
      sh 'npm install'  // Example command to install dependencies, adjust as needed
      
      // Display Hello, World! using Node.js
      sh 'echo "console.log(\'Hello, World!\')" > app.js'
      sh 'cat app.js'  // Debugging: Print the content of app.js to console
      def result = sh(script: 'node app.js', returnStatus: true)
      
      if (result == 0) {
        echo 'Node.js script executed successfully.'
      } else {
        error 'Node.js script execution failed.'
      }
      
    }
  }
}
