pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
         // Install any dependencies or run additional setup if needed
          sh 'npm --version'
          sh 'npm install'  // Example command to install dependencies, adjust as needed
          
          // Display Hello, World! using Node.js
          sh 'echo "console.log(\'Hello, World!\')" > app.js'
          sh 'node app.js'
      }
    }
  }
}
